application: drinkorder
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: static/images

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
